name: Trigger Rebuild on Hugging Face Space
on:
  push:
    branches:
      - main  # o il ramo che vuoi
jobs:
  rebuild:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git for Hugging Face Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Clone and update Hugging Face Space repository
        run: |
          git clone https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACENAME }}
          cd ${{ secrets.HF_SPACENAME }}
          
          # Crea il file Updates se non esiste
          touch Updates
          
          # Appende il timestamp al file Updates
          echo "$(date)" >> Updates
          
          # Controlla se ci sono modifiche da committare
          if git diff --quiet && git diff --staged --quiet; then
            echo "Nessuna modifica da committare"
            exit 0
          fi
          
          # Aggiungi e committa le modifiche
          git add Updates
          git commit -m "Update timestamp in Updates file - $(date)"
          
          # Push delle modifiche a Hugging Face
          git push https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACENAME }} main
      - name: Trigger Factory Rebuild on Hugging Face Space
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://huggingface.co/api/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACENAME }}/restart
