name: Trigger Rebuild on Hugging Face Space

on:
  push:
    branches:
      - main  # o il ramo che vuoi

jobs:
  rebuild:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git for Hugging Face Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Clone Hugging Face Space repository
        run: |
          git clone https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACENAME }}
          cd ${{ secrets.HF_SPACENAME }}

      - name: Append timestamp to Updates file
        run: |
          echo "$(date)" >> Updates  # Appende la data e l'ora corrente al file Updates
          git add Updates              # Aggiungi il file Updates alla staging area
          git commit -m "Update timestamp in Updates file"  # Commit con il messaggio desiderato

      - name: Push changes to Hugging Face Space
        run: |
          git push https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACENAME }} main
