name: Trigger Rebuild on Hugging Face Space
on:
  push:
    branches:
      - main  # o il ramo che vuoi
jobs:
  rebuild:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git for Hugging Face Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Clone and update Hugging Face Space repository
        run: |
          git clone https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACENAME }}
          cd ${{ secrets.HF_SPACENAME }}
          
          # Crea il file Updates se non esiste
          touch Updates
          
          # Appende il timestamp al file Updates
          echo "$(date)" >> Updates
          
          # Forza un rebuild senza cache creando/modificando un file dummy
          echo "# REBUILD_TIMESTAMP: $(date)" > .rebuild_trigger
          
          # Opzionalmente, modifica anche il Dockerfile in modo sicuro
          if [ -f "Dockerfile" ]; then
            # Rimuovi eventuali righe di timestamp precedenti
            sed -i '/^# REBUILD_TIMESTAMP:/d' Dockerfile
            # Inserisci il timestamp prima dell'ultima riga (CMD)
            sed -i '$i# REBUILD_TIMESTAMP: '"$(date)" Dockerfile
          fi
          
          # Controlla se ci sono modifiche da committare
          if git diff --quiet && git diff --staged --quiet; then
            echo "Nessuna modifica da committare"
            exit 0
          fi
          
          # Aggiungi e committa le modifiche
          git add Updates Dockerfile .rebuild_trigger
          git commit -m "Force rebuild - Update timestamp $(date)"
          
          # Push delle modifiche a Hugging Face
          git push https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACENAME }} main
